# Generated by Django 6.0.3 on 2026-03-30 23:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome e Sobrenome')),
                ('email', models.CharField(max_length=200, verbose_name='Email')),
                ('tel', models.CharField(max_length=50, unique=True, verbose_name='Telefone')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título do Livro')),
                ('autor', models.CharField(max_length=200, verbose_name='Autor do Livro')),
                ('isbn', models.CharField(max_length=50, unique=True, verbose_name='ISBN')),
                ('status', models.CharField(choices=[('EMPRESTADO', 'Emprestado'), ('DISPONIVEL', 'Disponivel')], default='DISPONIVEL', max_length=50)),
                ('qtd_estoque', models.CharField(max_length=50, unique=True, verbose_name='Quantidade em estoque')),
            ],
        ),
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_emprestimo', models.DateTimeField(auto_now_add=True)),
                ('data_prev_dev', models.DateTimeField(verbose_name='Previsao Devolucao')),
                ('data_devolucao', models.DateTimeField(blank=True, null=True, verbose_name='Data Devolução')),
                ('Cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='biblioteca.cliente', verbose_name='Responsável')),
                ('livro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='biblioteca.livro', verbose_name='Livro')),
            ],
        ),
    ]
